-- Test fixtures for a5 cookbook / quickstart / technical-details snippets.
-- Provides small deterministic lat/lng tables so the snippets that
-- aggregate or join real geographic data can parse and execute.
--
-- Idempotent: every CREATE uses OR REPLACE so re-running the harness on
-- the same connection is safe.

-- ---------------------------------------------------------------------
-- Base point set: 20 well-known city coordinates. Used as a building
-- block for every other table so all fixtures are mutually consistent.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TEMP TABLE _a5_cities AS
SELECT * FROM (VALUES
    (-74.0060,  40.7128, 'New York'),
    (-73.9352,  40.7306, 'Brooklyn'),
    (-73.9857,  40.7484, 'Midtown'),
    (-74.0445,  40.6892, 'Liberty'),
    (-73.7781,  40.6413, 'JFK'),
    (-118.2437, 34.0522, 'Los Angeles'),
    (-118.4085, 33.9416, 'LAX'),
    (-122.4194, 37.7749, 'San Francisco'),
    (-122.2711, 37.8044, 'Oakland'),
    (-122.0838, 37.3861, 'Mountain View'),
    ( -87.6298, 41.8781, 'Chicago'),
    ( -71.0589, 42.3601, 'Boston'),
    ( -77.0369, 38.9072, 'Washington DC'),
    ( -80.1918, 25.7617, 'Miami'),
    ( -95.3698, 29.7604, 'Houston'),
    (  -3.7037, 40.4168, 'Madrid'),
    (   2.3522, 48.8566, 'Paris'),
    (  -0.1276, 51.5074, 'London'),
    ( 139.6503, 35.6762, 'Tokyo'),
    ( 151.2093,-33.8688, 'Sydney')
) AS t(lon, lat, name);

-- ---------------------------------------------------------------------
-- `points` — referenced by metadata.json:quickStart.
-- Columns: longitude, latitude.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE points AS
SELECT lon AS longitude, lat AS latitude
FROM _a5_cities;

-- ---------------------------------------------------------------------
-- `pickups` — referenced by technical-details.mdx "What you can do".
-- Columns: longitude, latitude. 50 deterministic rows generated by
-- duplicating the city set with small lat/lng perturbations so GROUP BY
-- yields multiple rows per cell at typical resolutions.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE pickups AS
SELECT
    lon + (i * 0.0003) AS longitude,
    lat + (i * 0.0002) AS latitude
FROM _a5_cities,
     generate_series(0, 4) AS g(i);

-- ---------------------------------------------------------------------
-- `transactions` — referenced by cookbook.mdx aggregate + spatial-join.
-- Columns: longitude, latitude, amount, cell_15.
-- cell_15 is pre-computed at resolution 15 so the join example can
-- match the `events` CTE directly.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE transactions AS
SELECT
    lon + (i * 0.0001)                          AS longitude,
    lat + (i * 0.0001)                          AS latitude,
    (10.0 + i * 1.5)                            AS amount,
    a5_lonlat_to_cell(lon + (i * 0.0001),
                      lat + (i * 0.0001), 15)   AS cell_15
FROM _a5_cities,
     generate_series(0, 2) AS g(i);

-- ---------------------------------------------------------------------
-- `raw_points` — referenced by cookbook.mdx + technical-details.mdx
-- "roll up to a coarser resolution" examples.
-- Columns: lon, lat.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE raw_points AS
SELECT lon, lat FROM _a5_cities;

-- ---------------------------------------------------------------------
-- `indexed` — referenced by cookbook.mdx + technical-details.mdx
-- "roll up" snippets. Those blocks `CREATE TABLE indexed AS SELECT ...`
-- and then `SELECT ... FROM indexed`. The validator EXPLAINs each
-- statement before running it, so the second statement's reference to
-- `indexed` would fail at parse time. Pre-creating it (with the same
-- shape) makes EXPLAIN happy; the snippet's own CREATE OR REPLACE-style
-- semantics work because the executor uses CREATE TABLE which is fine
-- against a fresh validator session per slug.
-- Columns: lon, lat, cell_15.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE indexed AS
SELECT lon, lat, a5_lonlat_to_cell(lon, lat, 15) AS cell_15
FROM _a5_cities;

-- ---------------------------------------------------------------------
-- `event_points` — referenced by cookbook.mdx spatial-join example.
-- Columns: lon, lat.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE event_points AS
SELECT lon, lat FROM _a5_cities;

-- ---------------------------------------------------------------------
-- `zone_centroids` — referenced by cookbook.mdx spatial-join example.
-- Columns: lon, lat, zone_name.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE zone_centroids AS
SELECT lon, lat, name AS zone_name FROM _a5_cities;
