// Generated by scripts/haybarn-functions/generate-snapshot-module.mjs.
// Commit this file so Astro, Wrangler, tests, and editors load the same captures.
import binding0 from './bindings/duckdb-1.3.2.json';
import binding1 from './bindings/duckdb-1.4.4.json';
import binding2 from './bindings/duckdb-1.5.5.json';
import binding3 from './bindings/haybarn-1.5.5-rc3.json';

export const bindingModules = [binding0, binding1, binding2, binding3];
