// Generated by scripts/haybarn-functions/generate-snapshot-module.mjs.
// Commit this file so Astro, Wrangler, tests, and editors load the same snapshots.
import snapshot0 from './snapshots/duckdb-1.3.2.json';
import snapshot1 from './snapshots/duckdb-1.4.4.json';
import snapshot2 from './snapshots/duckdb-1.5.5.json';
import snapshot3 from './snapshots/haybarn-1.5.5-rc3.json';

export const snapshotModules = [snapshot0, snapshot1, snapshot2, snapshot3];
