direction: right

duckdb: DuckDB session {
  icon: ../../public/vgi/icons/duckdb.svg
  shape: cylinder

  ext: vgi extension {
    icon: https://cdn.simpleicons.org/cplusplus
  }
}

arrow: Apache Arrow IPC {
  icon: ../../public/vgi/icons/arrow.svg
  shape: hexagon
}

server: Your worker {
  grid-rows: 2

  python: Python {
    icon: https://cdn.simpleicons.org/python
  }
  typescript: TypeScript {
    icon: https://cdn.simpleicons.org/typescript
  }
  go: Go {
    icon: https://cdn.simpleicons.org/go
  }
  rust: Rust {
    icon: https://cdn.simpleicons.org/rust
  }
  java: Java {
    icon: https://cdn.simpleicons.org/openjdk
  }
  cpp: C++ {
    icon: https://cdn.simpleicons.org/cplusplus
  }
}

duckdb.ext <-> arrow: request / response
arrow <-> server: pipes • unix sockets • shared memory • HTTP
